name: order-data
cluster_name: test-dev


#minMemory: '<minMemory>' # default value "128Mi"
#maxMemory: '<maxMemory>' # default value "512Mi"
#maxCPU: '<maxCPU >' # default value "500m"

#env:
#  TRACER_URL: "https://tempo-distributor.helm-dev.npaws.zopsmart.com"
#  cloud: GCP
#  TRACER_URL: http://tempo-distributor.tempo:9411  # url values changes depending on the environment
#  TRACER_EXPORTER: zipkin